### PR TITLE
upgrade to netstandard2.0 and net5 for unit tests

### PR DESCRIPTION
**Pull request by jjmanton**
We are transitioning a large project towards net 5, and having this library support net standard would go a long way in helping ease our transition. Thanks!

### CODE REVIEW

**Comment by KevinDockx** [comment]
First of all: thanks for the PR! :)  

But I have to say I'm a bit hesitant to switch to netstandard2.0 as it would mean support for older framework/platform versions (like the .NET Framework 4.0 up to 4.6.1) would be removed.  I could consider a multitarget solution though, something along the lines of <TargetFrameworks>netstandard2.0;net45;net40</TargetFrameworks> for Marvin.JsonPatch, and net40;net45;net5 for the unit tests.  If that's ok for you, please update the PR accordingly.  

Another option for you could be to switch to Microsoft.AspNetCore.JsonPatch - that started out as a port of Marvin.JsonPatch I created for ASP.NET Core when Core 1.x was still in development.  It's since been updated with each new ASP.NET Core version.

**Comment by jjmanton** [comment]
@KevinDockx Thanks! I didnt even think about that, I'll make the changes to multi-target.

We plan on switching eventually, but currently we are trying to port all of our class libraries to standard, and then upgrade the web hosts to net 5. We use this library in a class lib, so we need net standard compatibility for now. It is a pretty massive solution, and this will help us ease into the transition. Thanks for considering this one!

**Comment by KevinDockx** [comment]
Thanks!  I'll give this a try over the weekend and if all goes well push a new version on Monday :)

**Comment by jjmanton** [comment]
I’m not 100% confident on the unit test net40 TFM. I had to use a much older version of xunit to make it work. If you see anything wrong or have suggestions, let me know. Thanks again for considering this one.

**Comment by KevinDockx** [comment]
Hmm, it seems like MyGet (which I use for building/deploying to NuGet) doesn't play nice with .NET 5 yet.  Do you need the unit tests to explicitly target net5.0, or would you be ok with it targeting an older version?  Marvin.JsonPatch itself would of course keep on multi-targeting netstandard20 etc.

**Comment by jjmanton** [comment]
@KevinDockx We shouldn't need net5, we just want to make sure one of the test targets picks up the net standard binary. I think netcore3 should do that, if MyGet works with that TFM?

**Comment by KevinDockx** [comment]
Done => https://www.nuget.org/packages/Marvin.JsonPatch/ :)

**Pull request merged**
