### PR TITLE
Backport Dictionary support from core implementation

### PR DESCRIPTION
**Pull request by MartyZhou**
@KevinDockx 
This is for [issue 58 Backport Dictionary support from core implementation](https://github.com/KevinDockx/JsonPatch/issues/58).

I basically moved dotnet core implementation to this repository.
changes:

- moved PocoAdapter, ListAdapter and DictionaryAdapter so it will support dictionary. DynamicObjectAdapter is not moved.
- moved dictionary related unit tests.

### CODE REVIEW

**Comment by KevinDockx** [comment]
That's one huge PR :)  Thanks for this, I'll look into it as soon as possible!

**Comment by KevinDockx** [comment]
@MartyZhou : quick question: which version did you backport this from?  Trying to get an idea of what's included from the current build of Microsoft.AspNetCore.JsonPatch and what isn't.  Thanks!

**Comment by MartyZhou** [comment]
@KevinDockx, this is ported from aspnet/jsonpatch dev branch.

**Comment by KevinDockx** [comment]
Thanks!  I'll merge this for now, and I'll have a look at the last stable version (not the dev branch) to see whether changes have to be made.  In any case, this will be in the next release - should be soon :-)

**Pull request merged**
